// Golden-vector generator for the Rust v11-manifest port.
// Runs against listam's installed hypercore 11.x / corestore 7.x so the
// vectors are ground truth for what the apps actually put on the wire.
//
// Usage: node gen-vectors.mjs > ../testdata/vectors.json
import { createRequire } from 'node:module'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const require = createRequire(
  new URL('../../../listam-headless/package.json', import.meta.url)
)

const crypto = require('hypercore-crypto')
const b4a = require('b4a')
const c = require('compact-encoding')
const Verifier = require('hypercore/lib/verifier.js')
const m = require('hypercore/lib/messages.js')
const caps = require('hypercore/lib/caps.js')
const Corestore = require('corestore')

const hex = (b) => b4a.toString(b, 'hex')

// --- deterministic single-signer v1 manifest (custom namespace) ---
const keyPair = crypto.keyPair(b4a.alloc(32, 7))
const namespace = b4a.alloc(32, 0xab)
const manifest = Verifier.createManifest({
  version: 1,
  signers: [{ publicKey: keyPair.publicKey, namespace }]
})
const encodedManifest = c.encode(m.manifest, manifest)
const manifestHash = Verifier.manifestHash(manifest)

// --- default-namespace variant (what a bare `new Hypercore` would create) ---
const defManifest = Verifier.createManifest(
  Verifier.defaultSignerManifest(keyPair.publicKey)
)
const defEncoded = c.encode(m.manifest, defManifest)
const defHash = Verifier.manifestHash(defManifest)

// --- v1 tree signable + assembled (multisig-wrapped) signature ---
const treeHash = b4a.alloc(32, 0x42)
const length = 4
const fork = 0
const signable = caps.treeSignable(manifestHash, treeHash, length, fork)
const rawSignature = crypto.sign(signable, keyPair.secretKey)
const assembled = c.encode(m.multiSignature, {
  proofs: [{ signer: 0, signature: rawSignature, patch: 0 }],
  patch: []
})
// self-check: JS verifies its own vector
if (!crypto.verify(signable, rawSignature, keyPair.publicKey)) {
  throw new Error('vector self-check failed: raw signature does not verify')
}

// --- a real corestore 7 core, deterministic via fixed primaryKey ---
const dir = mkdtempSync(join(tmpdir(), 'leaf-vectors-'))
const store = new Corestore(dir, { primaryKey: b4a.alloc(32, 9), unsafe: true })
const core = store.get({ name: 'leaf-spike' })
await core.ready()
await core.append([b4a.from('alpha'), b4a.from('bravo'), b4a.from('charlie')])
const realManifest = core.manifest
const realEncoded = c.encode(m.manifest, realManifest)
const realTreeHash = await core.treeHash()
if (!b4a.equals(Verifier.manifestHash(realManifest), core.key)) {
  throw new Error('vector self-check failed: real core key != manifestHash')
}

const out = {
  comment: 'Generated by gen-vectors.mjs against listam-headless node_modules',
  hypercoreVersion: require('hypercore/package.json').version,
  corestoreVersion: require('corestore/package.json').version,
  signerSeed: hex(b4a.alloc(32, 7)),
  publicKey: hex(keyPair.publicKey),
  namespace: hex(namespace),
  manifest: {
    encoded: hex(encodedManifest),
    hash: hex(manifestHash)
  },
  defaultNamespaceManifest: {
    encoded: hex(defEncoded),
    hash: hex(defHash)
  },
  treeSignable: {
    treeHash: hex(treeHash),
    length,
    fork,
    signable: hex(signable),
    rawSignature: hex(rawSignature),
    assembledSignature: hex(assembled)
  },
  realCore: {
    primaryKey: hex(b4a.alloc(32, 9)),
    name: 'leaf-spike',
    key: hex(core.key),
    discoveryKey: hex(core.discoveryKey),
    manifestEncoded: hex(realEncoded),
    signerPublicKey: hex(realManifest.signers[0].publicKey),
    signerNamespace: hex(realManifest.signers[0].namespace),
    length: core.length,
    treeHash: hex(realTreeHash)
  }
}

console.log(JSON.stringify(out, null, 2))
await store.close()
rmSync(dir, { recursive: true, force: true })
